### ISSUE TITLE
Error while reading local AEM SDK version 

### ISSUE THREAD

**Issue by chandrakanthkondari** [wcm-io/io.wcm.maven.aem-cloud-dependencies#68]
HI @stefanseifert ,

Product info url is leading to blank page, seems the url need to be corrected to system/console/productinfo.txt instead of /system/console/status-productinfo.txt 
https://github.com/wcm-io/io.wcm.maven.aem-cloud-dependencies/blob/48f87ad572002258db289647b89858b980863f4e/update-aem-deps.groovy#L147

**Comment by stefanseifert** [comment]
both URLs `/system/console/productinfo` and `/system/console/status-productinfo.txt` point more or less to the same information, but the latter is easier to parse because of text output. but the problem is, that the latter only returns the actual AEMaaCS SDK version if a "license.properties" file is present in the folder with the quickstart jar (a legacy from AEM 6.5 quickstart jars).

but you're right - we can simple switch to `/system/console/productinfo` to obtain the version from the HTML blurb using the same parsing logic.
